name: Deploy ShowDB maven

on:
  push:
    branches:
      - v1-dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get Version
        id: version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Deploy Snapshot Maven package
        if:  endsWith(steps.version.outputs.version, '-SNAPSHOT')
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_args: '-DskipTests'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
          
      - name: Deploy Release Maven package
        if:  endsWith(steps.version.outputs.version, '-SNAPSHOT') == false
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_args: '-DskipTests'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
          
