name: Deploy ShowDB Snapshot to Maven Central

on:
  push:
    branches:
      - v1-dev

env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B clean install -P release-sign-artifacts

    - name: Deploy Snapshot to Maven Central
      run: mvn -DskipTests=true deploy -Dmaven.deploy.skip=false -Dmaven.deploy.redeploy=true
