name: Publish Snapshot

on:
  push:
    branches:
      - main

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish Snapshot
        run: |
          mvn clean package
          mvn deploy -DskipTests -Dmaven.deploy.skip=true -Dmaven.javadoc.skip=true --settings ${{ secrets.MAVEN_SETTINGS }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}


