name: Snapshot Deploy

on:
  push:
    branches:
      - v1-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Set up GPG key
      uses: crazy-max/ghaction-import-gpg@v1
      with:
        key: ${{ secrets.GPG_SECRET }}
        passphrase: ${{ secrets.GPG_PASSWORD }}

    - name: Build and deploy
      run: |
        mvn -B clean deploy -DskipTests -Psnapshot -Dmaven.javadoc.skip=true -Dgpg.passphrase="${{ secrets.GPG_PASSWORD }}" --settings ${{ secrets.MAVEN_SETTINGS }}
